"""Streamlit app: paste a notice, get the plain version, a diff, and a
preserved-facts checklist.

The checklist is the point. It runs the deterministic faithfulness gate so a
reviewer can see, fact by fact, that the rewrite kept the amount, the dates, the
action, and the appeal rights. A readable rewrite that drops a fact shows a red X,
which is exactly the failure readability scores miss.

Pick a holdout notice (its operative facts are known, so the checklist is exact).
With ANTHROPIC_API_KEY set, the plain version is generated by the base-prompted
baseline; without a key, the gold reference target is shown so the app still demos.

Run:  streamlit run app/app.py
"""

from __future__ import annotations

import difflib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import streamlit as st

from app._ui import apply_theme, footer, header
from src.config import TARGET_GRADE, has_llm
from src.faithfulness import check_faithfulness
from src.readability import flesch_kincaid_grade
from src.schema import NoticePair

HOLDOUT = Path(__file__).resolve().parent.parent / "data" / "holdout.jsonl"

st.set_page_config(page_title="Plain-language notices", layout="wide")
apply_theme(st)
header(
    st,
    "Safety-Net AI · Fine-tuning",
    "Plain-language benefit notices",
    "Rewrite a bureaucratic notice into plain language while preserving every "
    "operative fact. The checklist runs a deterministic faithfulness gate: a "
    "readable rewrite that drops the appeal deadline or changes the amount fails.",
)

pairs = [NoticePair(**json.loads(l)) for l in HOLDOUT.read_text().splitlines() if l.strip()]
if not pairs:
    st.error("No holdout notices. Run `python data/generate_pairs.py` first.")
    st.stop()

choice = st.selectbox("Holdout notice", [p.id for p in pairs])
pair = next(p for p in pairs if p.id == choice)

use_llm = has_llm() and st.sidebar.checkbox("Generate with base-prompted Claude", value=False)

if use_llm:
    from src.baselines import base_prompted_rewrite
    with st.spinner("Generating plain rewrite..."):
        plain, _, _, _ = base_prompted_rewrite(pair.original)
    source = "base-prompted Claude"
else:
    plain = pair.target
    source = "gold reference target" + ("" if has_llm() else " (no API key set)")

c1, c2 = st.columns(2)
with c1:
    st.subheader("Original (bureaucratic)")
    st.write(pair.original)
    st.metric("Flesch-Kincaid grade", flesch_kincaid_grade(pair.original))
with c2:
    st.subheader(f"Plain version — {source}")
    st.write(plain)
    grade = flesch_kincaid_grade(plain)
    st.metric("Flesch-Kincaid grade", grade, delta=round(grade - flesch_kincaid_grade(pair.original), 1))
    if grade <= TARGET_GRADE:
        st.success(f"At or below the target reading grade ({TARGET_GRADE:.0f}).")
    else:
        st.warning(f"Above the target reading grade ({TARGET_GRADE:.0f}).")

st.subheader("Preserved-facts checklist (the gate)")
result = check_faithfulness(pair.operative_facts, plain)
for c in result.checks:
    icon = "✅" if c.preserved else "❌"
    st.markdown(f"{icon} **{c.fact}** — {c.detail}")
if result.passed:
    st.success("All operative facts preserved. Safe to send.")
else:
    st.error("An operative fact was dropped or altered. This rewrite must not ship.")

with st.expander("Word-level diff"):
    diff = difflib.unified_diff(pair.original.split(), plain.split(), lineterm="", n=0)
    st.code("\n".join(list(diff)[2:]) or "(identical)")

footer(st, "Synthetic notices, no PII · readability paired with a faithfulness gate")
